#!/usr/bin/env bash
#configures a new Ubuntu machine nginx

apt update
apt install -y software-properties-common
apt install haproxy

printf %s "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
	bind 0.0.0.0:80
    	mode http
    	stats enable
    	stats uri /haproxy?stats
        balance roundrobin
        server 205804-web-01 52.3.243.103:80 check
        server 205804-web-02 100.26.157.206:80 check
" >>  /etc/haproxy/haproxy.cfg

service haproxy start
