#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt update
apt install -y software-properties-common
apt install haproxy
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 205804-web-01 52.3.243.103:80 check
        server 205804-web-02 100.26.157.206:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
