#!/usr/bin/env bash
# Displays "bad luck" if 4 and "good luck" if 8

cnt=0

while [ $cnt -lt 10 ]
do
	if [ $cnt == 3 ]
	then
		echo "bad luck"
	elif [ $cnt == 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( cnt++ ))
done
